export const SEARCH_REQUEST_IDLE = "SEARCH_REQUEST_IDLE";
export const SEARCH_REQUEST_STARTED = "SEARCH_REQUEST_STARTED";
export const SEARCH_REQUEST_COMPLETED = "SEARCH_REQUEST_COMPLETED";
export const SEARCH_REQUEST_ERROR = "SEARCH_REQUEST_ERROR";